# import pandas as pd

In [4]:
pd = pd.read_csv('D:/Player.csv')

In [7]:
pd.head(20)

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
5,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
6,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
7,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
8,9,JH Kallis,16-Oct-75,Right_Hand,Right-arm fast-medium,South Africa,0,NaN
9,10,CL White,18-Aug-83,Right_Hand,Legbreak googly,Australia,0,NaN
10,11,MV Boucher,3-Dec-76,Right_Hand,Right-arm medium,South Africa,0,NaN
11,12,B Akhil,7-Oct-77,Right_Hand,Right-arm medium-fast,India,0,NaN
12,13,AA Noffke,30-Apr-77,Right_Hand,Right-arm fast-medium,Australia,0,NaN
13,14,P Kumar,2-Oct-86,Right_Hand,Right-arm medium,India,0,NaN
14,15,Z Khan,7-Oct-78,Right_Hand,Left-arm fast-medium,India,0,NaN
15,16,SB Joshi,6-Jun-70,Left_Hand,Slow left-arm orthodox,India,0,NaN
16,17,PA Patel,9-Mar-85,Left_Hand,NaN,India,0,NaN
17,18,ML Hayden,29-Oct-71,Left_Hand,Right-arm medium,Australia,0,NaN
18,19,MEK Hussey,27-May-75,Left_Hand,Right-arm medium,Australia,0,NaN
19,20,MS Dhoni,7-Jul-81,Right_Hand,Right-arm medium,India,0,NaN

In [8]:
pd.tail(10)

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
513,514,I Shivram,NaN,NaN,NaN,India,1,NaN
514,515,SD Ranade,NaN,NaN,NaN,India,1,NaN
515,516,TH Wijewardene,NaN,NaN,NaN,Sri Lanka,1,NaN
516,517,AL Hill,NaN,NaN,NaN,New Zealand,1,NaN
517,518,RJ Tucker,NaN,NaN,NaN,Australia,1,NaN
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [10]:
df = pd.read_csv('D:/Player.csv')

In [11]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df1 = df.head()

In [13]:
df.tail()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [23]:
df1.to_csv("test.csv")

In [18]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [21]:
pwd()

'C:\\Users\\deepak.thakur\\ineuro\\Class Lectures'

In [24]:
pd.read_csv('test.csv')

,Unnamed: 0,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN

In [36]:
df = pd.read_csv('D:/Player.csv', sep='#',header = None, names = ['a','b','c','d','e','f','g','h'], skiprows=[0,2,5])

In [37]:
df

,a,b,c,d,e,f,g,h
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
2,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
3,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
4,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
...,...,...,...,...,...,...,...,...
516,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
517,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
518,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
519,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
520,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [44]:
df = pd.read_csv('D:/Player.csv', sep='#', na_values=['SC Ganguly','BB McCullum'])

In [45]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,NaN,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,NaN,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [46]:
df1 = pd.read_csv('D:/Player.csv', sep = "#", skiprows=[0,1,2])

In [47]:
df1

,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,Unnamed: 7
0,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
1,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
2,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
3,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
4,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
...,...,...,...,...,...,...,...,...
515,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
516,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
517,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
518,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
519,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [48]:
type(df)

pandas.core.frame.DataFrame

In [49]:
type(df1)

pandas.core.frame.DataFrame

In [50]:
df.describe()

        Player_Id   Is_Umpire  Unnamed: 7
count  523.000000  523.000000   12.000000
mean   262.003824    0.099426    6.500000
std    151.127981    0.299520    3.605551
min      1.000000    0.000000    1.000000
25%    131.500000    0.000000    3.750000
50%    262.000000    0.000000    6.500000
75%    392.500000    0.000000    9.250000
max    524.000000    1.000000   12.000000

In [52]:
df.dtypes

Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [54]:
df.dtypes

Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [ ]:
df1 = pd.read_csv('D:/Player.csv', sep = "#")

In [55]:
df1

,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,Unnamed: 7
0,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
1,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
2,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
3,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
4,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
...,...,...,...,...,...,...,...,...
515,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
516,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
517,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
518,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
519,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [63]:
df1.to_csv("result4.csv", index = False, sep = "#", columns = ['Player_Id', 'DOB'])

KeyError: "None of [Index(['Player_Id', 'DOB'], dtype='object')] are in the [columns]"

In [64]:
df = pd.read_csv('D:/Player.csv', sep = "#")

In [65]:
df

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [66]:
df.tail()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [79]:
df.columns

Index(['Player_Id', 'Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill',
       'Country', 'Is_Umpire', 'Unnamed: 7'],
      dtype='object')

In [72]:
df['Player_Id']

0        1
1        2
2        3
3        4
4        5
      ...
518    519
519    520
520    521
521    523
522    524
Name: Player_Id, Length: 523, dtype: int64

In [71]:
type(df['Player_Id'])

pandas.core.series.Series

In [73]:
df[['Player_Id']]

     Player_Id
0            1
1            2
2            3
3            4
4            5
..         ...
518        519
519        520
520        521
521        523
522        524

[523 rows x 1 columns]

In [74]:
type(df[['Player_Id']])

pandas.core.frame.DataFrame

In [77]:
df[['Player_Id', 'Batting_Hand']]

     Player_Id Batting_Hand
0            1    Left_Hand
1            2   Right_Hand
2            3   Right_Hand
3            4   Right_Hand
4            5   Right_Hand
..         ...          ...
518        519          NaN
519        520          NaN
520        521          NaN
521        523   Right_Hand
522        524   Right_Hand

[523 rows x 2 columns]

In [78]:
df[['Player_Id', 'Batting_Hand', 'Is_Umpire']]

     Player_Id Batting_Hand  Is_Umpire
0            1    Left_Hand          0
1            2   Right_Hand          0
2            3   Right_Hand          0
3            4   Right_Hand          0
4            5   Right_Hand          0
..         ...          ...        ...
518        519          NaN          1
519        520          NaN          1
520        521          NaN          1
521        523   Right_Hand          0
522        524   Right_Hand          0

[523 rows x 3 columns]

In [83]:
df2 = pd.read_excel('D:\sample-excel-master\LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx', sheet_name='Create your instrument universe')

In [84]:
df4 = pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")

In [85]:
df4

[       Season   Age                                   Team  \
 0     2008-09  19.0  Did Not Play (other pro league—Spain)
 1     2009-10  20.0                                    OKC
 2     2010-11  21.0                                    OKC
 3     2011-12  22.0                                    OKC
 4     2012-13  23.0                                    OKC
 5     2013-14  24.0                                    OKC
 6     2014-15  25.0                                    OKC
 7     2015-16  26.0                                    OKC
 8     2016-17  27.0                                    TOT
 9     2016-17  27.0                                    ORL
 10    2016-17  27.0                                    TOR
 11    2017-18  28.0                                    TOR
 12    2018-19  29.0                                    TOR
 13    2019-20  30.0                                    TOR
 14    2020-21  31.0                                    LAC
 15     Career   NaN                                    NaN
 16        NaN   NaN                                    NaN
 17  7 seasons   NaN                                    OKC
 18  4 seasons   NaN                                    TOR
 19   1 season   NaN                                    ORL
 20   1 season   NaN                                    LAC

                                        Lg  \
 0   Did Not Play (other pro league—Spain)
 1                                     NBA
 2                                     NBA
 3                                     NBA
 4                                     NBA
 5                                     NBA
 6                                     NBA
 7                                     NBA
 8                                     NBA
 9                                     NBA
 10                                    NBA
 11                                    NBA
 12                                    NBA
 13                                    NBA
 14                                    NBA
 15                                    NBA
 16                                    NaN
 17                                    NBA
 18                                    NBA
 19                                    NBA
 20                                    NBA

                                       Pos  \
 0   Did Not Play (other pro league—Spain)
 1                                      PF
 2                                      PF
 3                                      PF
 4                                      PF
 5                                      PF
 6                                      PF
 7                                      PF
 8                                      PF
 9                                      PF
 10                                     PF
 11                                     PF
 12                                      C
 13                                      C
 14                                      C
 15                                    NaN
 16                                    NaN
 17                                    NaN
 18                                    NaN
 19                                    NaN
 20                                    NaN

                                         G  \
 0   Did Not Play (other pro league—Spain)
 1                                      73
 2                                      82
 3                                      66
 4                                      80
 5                                      81
 6                                      64
 7                                      78
 8                                      79
 9                                      56
 10                                     23
 11                                     76
 12                                     74
 13                                     55
 14                                     41
 15                                    849
 16                                    NaN
 17                                    524
 18                                    228
 19                                     56
 20                                     41

                                        GS  \
 0   Did Not Play (other pro league—Spain)
 1                                       0
 2                                      44
 3                                      66
 4                                      80
 5                                      81
 6                                      64
 7                                      78
 8                                      79
 9                                      56
 10                                     23
 11                                     76
 12                                     51
 13                                     27
 14                                     39
 15                                    685
 16                                    NaN
 17                                    413
 18                                    177
 19                                     56
 20                                     39

                                        MP  \
 0   Did Not Play (other pro league—Spain)
 1                                    18.1
 2                                    27.0
 3                                    27.2
 4                                    31.1
 5                                    32.9
 6                                    33.1
 7                                    32.1
 8                                    30.7
 9                                    30.5
 10                                   31.0
 11                                   27.5
 12                                   27.2
 13                                   27.0
 14                                   23.3
 15                                   28.3
 16                                    NaN
 17                                   28.8
 18                                   27.6
 19                                   30.5
 20                                   23.3

                                        FG  \
 0   Did Not Play (other pro league—Spain)
 1                                     2.8
 2                                     4.1
 3                                     4.0
 4                                     5.6
 5                                     6.5
 6                                     5.8
 7                                     5.3
 8                                     6.0
 9                                     6.1
 10                                    5.6
 11                                    5.0
 12                                    6.3
 13                                    6.2
 14                                    4.5
 15                                    5.2
 16                                    NaN
 17                                    4.9
 18                                    5.8
 19                                    6.1
 20                                    4.5

                                       FGA  ...  \
 0   Did Not Play (other pro league—Spain)  ...
 1                                     5.1  ...
 2                                     7.5  ...
 3                                     7.4  ...
 4                                     9.7  ...
 5                                    12.1  ...
 6                                    12.3  ...
 7                                    11.1  ...
 8                                    12.4  ...
 9                                    12.6  ...
 10                                   12.1  ...
 11                                   10.3  ...
 12                                   11.9  ...
 13                                   12.2  ...
 14                                    8.9  ...
 15                                   10.1  ...
 16                                    NaN  ...
 17                                    9.3  ...
 18                                   11.4  ...
 19                                   12.6  ...
 20                                    8.9  ...

                                       FT%  \
 0   Did Not Play (other pro league—Spain)
 1                                    .630
 2                                    .750
 3                                    .661
 4                                    .749
 5                                    .784
 6                                    .836
 7                                    .752
 8                                    .856
 9                                    .846
 10                                   .882
 11                                   .797
 12                                   .763
 13                                   .718
 14                                   .811
 15                                   .759
 16                                    NaN
 17                                   .745
 18                                   .768
 19                                   .846
 20                                   .811

                                       ORB  \
 0   Did Not Play (other pro league—Spain)
 1                                     1.9
 2                                     2.6
 3                                     2.9
 4                                     2.8
 5                                     2.8
 6                                     2.1
 7                                     1.8
 8                                     1.6
 9                                     1.8
 10                                    1.3
 11                                    1.0
 12                                    2.1
 13                                    2.1
 14                                    1.8
 15                                    2.1
 16                                    NaN
 17                                    2.4
 18                                    1.7
 19                                    1.8
 20                                    1.8

                                       DRB  \
 0   Did Not Play (other pro league—Spain)
 1                                     3.5
 2                                     5.0
 3                                     4.6
 4                                     4.9
 5                                     6.0
 6                                     5.7
 7                                     5.0
 8                                     5.2
 9                                     5.0
 10                                    5.5
 11                                    5.3
 12                                    6.0
 13                                    6.1
 14                                    4.9
 15                                    5.2
 16                                    NaN
 17                                    5.0
 18                                    5.7
 19                                    5.0
 20                                    4.9

                                       TRB  \
 0   Did Not Play (other pro league—Spain)
 1                                     5.4
 2                                     7.6
 3                                     7.5
 4                                     7.7
 5                                     8.8
 6                                     7.8
 7                                     6.8
 8                                     6.8
 9                                     6.8
 10                                    6.8
 11                                    6.3
 12                                    8.1
 13                                    8.2
 14                                    6.7
 15                                    7.3
 16                                    NaN
 17                                    7.4
 18                                    7.4
 19                                    6.8
 20                                    6.7

                                       AST  \
 0   Did Not Play (other pro league—Spain)
 1                                     0.1
 2                                     0.3
 3                                     0.4
 4                                     0.5
 5                                     1.0
 6                                     0.9
 7                                     0.8
 8                                     0.9
 9                                     1.1
 10                                    0.7
 11                                    0.8
 12                                    1.3
 13                                    1.4
 14                                    1.8
 15                                    0.8
 16                                    NaN
 17                                    0.6
 18                                    1.1
 19                                    1.1
 20                                    1.8

                                       STL  \
 0   Did Not Play (other pro league—Spain)
 1                                     0.3
 2                                     0.4
 3                                     0.5
 4                                     0.4
 5                                     0.5
 6                                     0.5
 7                                     0.5
 8                                     0.5
 9                                     0.6
 10                                    0.3
 11                                    0.4
 12                                    0.4
 13                                    0.5
 14                                    0.2
 15                                    0.4
 16                                    NaN
 17                                    0.4
 18                                    0.4
 19                                    0.6
 20                                    0.2

                                       BLK  \
 0   Did Not Play (other pro league—Spain)
 1                                     1.3
 2                                     2.4
 3                                     3.7
 4                                     3.0
 5                                     2.7
 6                                     2.4
 7                                     1.9
 8                                     1.6
 9                                     1.6
 10                                    1.4
 11                                    1.3
 12                                    1.4
 13                                    0.8
 14                                    1.1
 15                                    2.0
 16                                    NaN
 17                                    2.5
 18                                    1.2
 19                                    1.6
 20                                    1.1

                                       TOV  \
 0   Did Not Play (other pro league—Spain)
 1                                     0.9
 2                                     0.9
 3                                     1.2
 4                                     1.6
 5                                     1.5
 6                                     1.5
 7                                     1.4
 8                                     1.3
 9                                     1.2
 10                                    1.7
 11                                    1.2
 12                                    1.5
 13                                    2.0
 14                                    1.1
 15                                    1.3
 16                                    NaN
 17                                    1.3
 18                                    1.5
 19                                    1.2
 20                                    1.1

                                        PF  \
 0   Did Not Play (other pro league—Spain)
 1                                     2.7
 2                                     3.3
 3                                     2.7
 4                                     2.7
 5                                     2.9
 6                                     3.0
 7                                     2.7
 8                                     2.7
 9                                     2.5
 10                                    3.3
 11                                    2.8
 12                                    2.9
 13                                    2.8
 14                                    1.9
 15                                    2.8
 16                                    NaN
 17                                    2.8
 18                                    2.8
 19                                    2.5
 20                                    1.9

                                       PTS
 0   Did Not Play (other pro league—Spain)
 1                                     6.3
 2                                     9.9
 3                                     9.1
 4                                    13.2
 5                                    15.1
 6                                    14.3
 7                                    12.6
 8                                    14.8
 9                                    15.1
 10                                   14.2
 11                                   12.6
 12                                   15.0
 13                                   15.4
 14                                   11.1
 15                                   12.5
 16                                    NaN
 17                                   11.6
 18                                   14.2
 19                                   15.1
 20                                   11.1

 [21 rows x 30 columns],
        Season   Age Team   Lg  Pos      G     GS    MP   FG   FGA  ...    FT%  \
 0     2009-10  20.0  OKC  NBA   PF    6.0    0.0  25.5  3.3   5.8  ...  0.700
 1     2010-11  21.0  OKC  NBA   PF   17.0   17.0  28.8  3.9   8.5  ...  0.825
 2     2011-12  22.0  OKC  NBA   PF   20.0   20.0  28.5  4.2   8.0  ...  0.722
 3     2012-13  23.0  OKC  NBA   PF   11.0   11.0  33.3  5.4  12.3  ...  0.792
 4     2013-14  24.0  OKC  NBA   PF   17.0   17.0  34.2  5.1   8.6  ...  0.765
 5     2015-16  26.0  OKC  NBA   PF   18.0   18.0  33.4  4.7   9.1  ...  0.750
 6     2016-17  27.0  TOR  NBA   PF   10.0   10.0  30.7  6.0  13.0  ...  0.846
 7     2017-18  28.0  TOR  NBA   PF   10.0    9.0  26.0  3.0   7.2  ...  0.818
 8     2018-19  29.0  TOR  NBA    C   24.0    0.0  20.8  3.8   8.0  ...  0.762
 9     2019-20  30.0  TOR  NBA    C   11.0    0.0  22.8  5.7  10.0  ...  1.000
 10    2020-21  31.0  LAC  NBA    C    2.0    0.0   9.0  1.5   3.0  ...  1.000
 11     Career   NaN  NaN  NBA  NaN  146.0  102.0  28.1  4.5   8.9  ...  0.792
 12        NaN   NaN  NaN  NaN  NaN    NaN    NaN   NaN  NaN   NaN  ...    NaN
 13  6 seasons   NaN  OKC  NBA  NaN   89.0   83.0  31.0  4.5   8.8  ...  0.768
 14  4 seasons   NaN  TOR  NBA  NaN   55.0   19.0  24.0  4.5   9.2  ...  0.824
 15   1 season   NaN  LAC  NBA  NaN    2.0    0.0   9.0  1.5   3.0  ...  1.000

     ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
 0   2.2  4.3  6.5  0.3  0.3  2.0  1.0  3.2   7.8
 1   2.8  4.5  7.3  0.2  0.2  3.1  1.2  3.8   9.8
 2   2.4  3.4  5.8  0.6  0.6  3.0  0.6  2.9   9.8
 3   3.5  4.8  8.4  0.7  0.0  3.0  0.6  3.5  12.8
 4   1.8  5.0  6.8  0.7  0.6  2.5  1.2  3.2  12.1
 5   1.3  5.0  6.3  0.6  0.8  1.3  0.5  2.8  12.0
 6   0.9  5.6  6.5  1.4  0.4  1.7  1.1  3.7  14.3
 7   1.3  4.6  5.9  1.1  0.1  1.3  1.6  2.1   8.7
 8   1.5  4.5  6.0  0.9  0.5  1.0  1.0  3.3   9.4
 9   1.5  6.2  7.7  1.2  0.2  1.3  1.1  2.5  14.8
 10  0.5  1.5  2.0  1.0  0.5  1.5  0.5  0.5   5.0
 11  1.9  4.7  6.5  0.7  0.4  2.0  1.0  3.1  11.0
 12  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 13  2.2  4.5  6.7  0.5  0.5  2.5  0.8  3.2  10.9
 14  1.3  5.1  6.4  1.1  0.3  1.2  1.2  3.0  11.2
 15  0.5  1.5  2.0  1.0  0.5  1.5  0.5  0.5   5.0

 [16 rows x 30 columns],
        Season   Age Team   Lg  Pos      G     GS       MP      FG     FGA  \
 0     2009-10  20.0  OKC  NBA   PF   73.0    0.0   1323.0   201.0   370.0

In [86]:
type(df4)

list

In [87]:
len(df4)

6

In [88]:
df4[0]

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2008-09,19.0,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),...,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain)
1,2009-10,20.0,OKC,NBA,PF,73,0,18.1,2.8,5.1,...,.630,1.9,3.5,5.4,0.1,0.3,1.3,0.9,2.7,6.3
2,2010-11,21.0,OKC,NBA,PF,82,44,27.0,4.1,7.5,...,.750,2.6,5.0,7.6,0.3,0.4,2.4,0.9,3.3,9.9
3,2011-12,22.0,OKC,NBA,PF,66,66,27.2,4.0,7.4,...,.661,2.9,4.6,7.5,0.4,0.5,3.7,1.2,2.7,9.1
4,2012-13,23.0,OKC,NBA,PF,80,80,31.1,5.6,9.7,...,.749,2.8,4.9,7.7,0.5,0.4,3.0,1.6,2.7,13.2
5,2013-14,24.0,OKC,NBA,PF,81,81,32.9,6.5,12.1,...,.784,2.8,6.0,8.8,1.0,0.5,2.7,1.5,2.9,15.1
6,2014-15,25.0,OKC,NBA,PF,64,64,33.1,5.8,12.3,...,.836,2.1,5.7,7.8,0.9,0.5,2.4,1.5,3.0,14.3
7,2015-16,26.0,OKC,NBA,PF,78,78,32.1,5.3,11.1,...,.752,1.8,5.0,6.8,0.8,0.5,1.9,1.4,2.7,12.6
8,2016-17,27.0,TOT,NBA,PF,79,79,30.7,6.0,12.4,...,.856,1.6,5.2,6.8,0.9,0.5,1.6,1.3,2.7,14.8
9,2016-17,27.0,ORL,NBA,PF,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
10,2016-17,27.0,TOR,NBA,PF,23,23,31.0,5.6,12.1,...,.882,1.3,5.5,6.8,0.7,0.3,1.4,1.7,3.3,14.2
11,2017-18,28.0,TOR,NBA,PF,76,76,27.5,5.0,10.3,...,.797,1.0,5.3,6.3,0.8,0.4,1.3,1.2,2.8,12.6
12,2018-19,29.0,TOR,NBA,C,74,51,27.2,6.3,11.9,...,.763,2.1,6.0,8.1,1.3,0.4,1.4,1.5,2.9,15.0
13,2019-20,30.0,TOR,NBA,C,55,27,27.0,6.2,12.2,...,.718,2.1,6.1,8.2,1.4,0.5,0.8,2.0,2.8,15.4
14,2020-21,31.0,LAC,NBA,C,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1
15,Career,NaN,NaN,NBA,NaN,849,685,28.3,5.2,10.1,...,.759,2.1,5.2,7.3,0.8,0.4,2.0,1.3,2.8,12.5
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,7 seasons,NaN,OKC,NBA,NaN,524,413,28.8,4.9,9.3,...,.745,2.4,5.0,7.4,0.6,0.4,2.5,1.3,2.8,11.6
18,4 seasons,NaN,TOR,NBA,NaN,228,177,27.6,5.8,11.4,...,.768,1.7,5.7,7.4,1.1,0.4,1.2,1.5,2.8,14.2
19,1 season,NaN,ORL,NBA,NaN,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
20,1 season,NaN,LAC,NBA,NaN,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1

In [91]:
df4[3].to_csv("palyer.csv")

In [2]:
import pandas as pd
df4 = pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")
for i in range(len(df4)):
    df4[i].to_csv(f"html_data{i}.csv")

In [94]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [99]:
s = '''{
"name" : "deep",
"phone_no" : 45454545,
"company" : ["ineuron","Convegenius", "pacific", "emds", "concentrix"]
}
'''

In [101]:
import json
s1 = json.loads(s)

In [103]:
pd.DataFrame(s1, columns=['company'])

       company
0      ineuron
1  Convegenius
2      pacific
3         emds
4   concentrix

In [125]:
import requests

In [126]:
res = requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')

In [127]:
res

In [128]:
js = res.json()

In [111]:
js[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41840',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41840/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41840/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41840/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/41840',
 'id': 912891173,
 'node_id': 'MDExOlB1bGxSZXF1ZXN0NjYzMDAzNDU2',
 'number': 41840,
 'title': 'doc: add highlight_quantile to style.rst',
 'user': {'login': 'attack68',
  'id': 24256554,
  'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/attack68',
  'html_url': 'https://github.com/attack68',
  'followers_url': 'https://api.github.com/users/attack68/followers',
  'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
  'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
  'organizations_url': 'https://api.github.com/users/attack68/orgs',
  'repos_url': 'https://api.github.com/users/attack68/repos',
  'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/attack68/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2021-06-06T17:05:00Z',
 'updated_at': '2021-06-06T17:05:00Z',
 'closed_at': None,
 'author_association': 'CONTRIBUTOR',
 'active_lock_reason': None,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41840',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41840',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/41840.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/41840.patch'},
 'body': 'oversight when adding the method.\r\n',
 'performed_via_github_app': None}

In [112]:
js[0]['user']

{'login': 'attack68',
 'id': 24256554,
 'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/attack68',
 'html_url': 'https://github.com/attack68',
 'followers_url': 'https://api.github.com/users/attack68/followers',
 'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
 'organizations_url': 'https://api.github.com/users/attack68/orgs',
 'repos_url': 'https://api.github.com/users/attack68/repos',
 'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/attack68/received_events',
 'type': 'User',
 'site_admin': False}

In [115]:
js[0]['title']

'doc: add highlight_quantile to style.rst'

In [117]:
for i in range(len(js)):
    print(js[i]['title'])

doc: add highlight_quantile to style.rst
DOC: Input/Output page contains only input functions
ENH: Using transparentpath in read_csv
ENH: DataFrame.to_expr() method
_libs.hashtable.ismember incorrect with tuples containing nan
BUG: Odd timezone offset change with old datetimes with tz_convert
REF: de-duplicate symmetric_difference, _union
REF: de-duplicate IntervalIndex setops
BUG: IntervalIndex([np.nan, np.nan]).is_monotonic returns True
TYP: datetimelike
CI: Re-enable Circle CI
ENH: retain attrs when concat dataframes
BUG: DataFrame `isin` function randomly selects values (instead of using them all) when on Intel CPU and input is a torch Tensor
ENH: Allow different senses of "distance" for method=nearest indexing
REF: share wrapping in MultiIndex setops
REF: de-duplicate Index._intersection + MultiIndex._intersection
BUG: MultiIndex.unique incorrect when NA value is present
DOC: Whatsnew1.3 grammar
BUG: wrong exception when slicing on TimedeltaIndex
BUG: read_csv does not read double double quotes in pipe delimited txt file
DOC/BLD: update README.md, list setuptools as dependency
BUG: pd.util.hash_array fails on DatetimeIndex with tz specified
DEPS: clarifying setuptools's status as a dependency
Axis behaviour not consistent for df.interpolate for pad with `limit_area` passed.
TYP: Numpy compatibility of definition of "array like"
BUG:
BUG: combine_first fails when one series is timezone-aware and the other is emtpy.
BUG: undocumented astype("category").astype(str) type inconsistency between pandas 1.1 & 1.2
BUG: `round()` for 5e5 ms should be `ceil()`
BUG: Broken bool supports in pandas' quantile by NumPy's percentile behaviour change

In [119]:
pd.DataFrame(js, columns=['url', 'title'])

,url,title
0,https://api.github.com/repos/pandas-dev/pandas...,doc: add highlight_quantile to style.rst
1,https://api.github.com/repos/pandas-dev/pandas...,DOC: Input/Output page contains only input fun...
2,https://api.github.com/repos/pandas-dev/pandas...,ENH: Using transparentpath in read_csv
3,https://api.github.com/repos/pandas-dev/pandas...,ENH: DataFrame.to_expr() method
4,https://api.github.com/repos/pandas-dev/pandas...,_libs.hashtable.ismember incorrect with tuples...
5,https://api.github.com/repos/pandas-dev/pandas...,BUG: Odd timezone offset change with old datet...
6,https://api.github.com/repos/pandas-dev/pandas...,"REF: de-duplicate symmetric_difference, _union"
7,https://api.github.com/repos/pandas-dev/pandas...,REF: de-duplicate IntervalIndex setops
8,https://api.github.com/repos/pandas-dev/pandas...,"BUG: IntervalIndex([np.nan, np.nan]).is_monoto..."
9,https://api.github.com/repos/pandas-dev/pandas...,TYP: datetimelike
10,https://api.github.com/repos/pandas-dev/pandas...,CI: Re-enable Circle CI
11,https://api.github.com/repos/pandas-dev/pandas...,ENH: retain attrs when concat dataframes
12,https://api.github.com/repos/pandas-dev/pandas...,BUG: DataFrame `isin` function randomly select...
13,https://api.github.com/repos/pandas-dev/pandas...,"ENH: Allow different senses of ""distance"" for ..."
14,https://api.github.com/repos/pandas-dev/pandas...,REF: share wrapping in MultiIndex setops
15,https://api.github.com/repos/pandas-dev/pandas...,REF: de-duplicate Index._intersection + MultiI...
16,https://api.github.com/repos/pandas-dev/pandas...,BUG: MultiIndex.unique incorrect when NA value...
17,https://api.github.com/repos/pandas-dev/pandas...,DOC: Whatsnew1.3 grammar
18,https://api.github.com/repos/pandas-dev/pandas...,BUG: wrong exception when slicing on Timedelta...
19,https://api.github.com/repos/pandas-dev/pandas...,BUG: read_csv does not read double double quot...
20,https://api.github.com/repos/pandas-dev/pandas...,"DOC/BLD: update README.md, list setuptools as ..."
21,https://api.github.com/repos/pandas-dev/pandas...,BUG: pd.util.hash_array fails on DatetimeIndex...
22,https://api.github.com/repos/pandas-dev/pandas...,DEPS: clarifying setuptools's status as a depe...
23,https://api.github.com/repos/pandas-dev/pandas...,Axis behaviour not consistent for df.interpola...
24,https://api.github.com/repos/pandas-dev/pandas...,"TYP: Numpy compatibility of definition of ""arr..."
25,https://api.github.com/repos/pandas-dev/pandas...,BUG:
26,https://api.github.com/repos/pandas-dev/pandas...,BUG: combine_first fails when one series is ti...
27,https://api.github.com/repos/pandas-dev/pandas...,"BUG: undocumented astype(""category"").astype(st..."
28,https://api.github.com/repos/pandas-dev/pandas...,BUG: `round()` for 5e5 ms should be `ceil()`
29,https://api.github.com/repos/pandas-dev/pandas...,BUG: Broken bool supports in pandas' quantile ...

In [121]:
df4 = pd.DataFrame(js)

In [ ]:
df4.to_csv("")

In [129]:
l = []
for i in range(len(js)):
    l.append(js[i]['user'])
pd.DataFrame(l)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
1,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
2,michaelshekasta,41590425,MDQ6VXNlcjQxNTkwNDI1,https://avatars.githubusercontent.com/u/415904...,,https://api.github.com/users/michaelshekasta,https://github.com/michaelshekasta,https://api.github.com/users/michaelshekasta/f...,https://api.github.com/users/michaelshekasta/f...,https://api.github.com/users/michaelshekasta/g...,https://api.github.com/users/michaelshekasta/s...,https://api.github.com/users/michaelshekasta/s...,https://api.github.com/users/michaelshekasta/orgs,https://api.github.com/users/michaelshekasta/r...,https://api.github.com/users/michaelshekasta/e...,https://api.github.com/users/michaelshekasta/r...,User,False
3,kerrickstaley,184773,MDQ6VXNlcjE4NDc3Mw==,https://avatars.githubusercontent.com/u/184773...,,https://api.github.com/users/kerrickstaley,https://github.com/kerrickstaley,https://api.github.com/users/kerrickstaley/fol...,https://api.github.com/users/kerrickstaley/fol...,https://api.github.com/users/kerrickstaley/gis...,https://api.github.com/users/kerrickstaley/sta...,https://api.github.com/users/kerrickstaley/sub...,https://api.github.com/users/kerrickstaley/orgs,https://api.github.com/users/kerrickstaley/repos,https://api.github.com/users/kerrickstaley/eve...,https://api.github.com/users/kerrickstaley/rec...,User,False
4,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
5,rok,54589,MDQ6VXNlcjU0NTg5,https://avatars.githubusercontent.com/u/54589?v=4,,https://api.github.com/users/rok,https://github.com/rok,https://api.github.com/users/rok/followers,https://api.github.com/users/rok/following{/ot...,https://api.github.com/users/rok/gists{/gist_id},https://api.github.com/users/rok/starred{/owne...,https://api.github.com/users/rok/subscriptions,https://api.github.com/users/rok/orgs,https://api.github.com/users/rok/repos,https://api.github.com/users/rok/events{/privacy},https://api.github.com/users/rok/received_events,User,False
6,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
7,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
8,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
9,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
10,lithomas1,47963215,MDQ6VXNlcjQ3OTYzMjE1,https://avatars.githubusercontent.com/u/479632...,,https://api.github.com/users/lithomas1,https://github.com/lithomas1,https://api.github.com/users/lithomas1/followers,https://api.github.com/users/lithomas1/followi...,https://api.github.com/users/lithomas1/gists{/...,https://api.github.com/users/lithomas1/starred...,https://api.github.com/users/lithomas1/subscri...,https://api.github.com/users/lithomas1/orgs,https://api.github.com/users/lithomas1/repos,https://api.github.com/users/lithomas1/events{...,https://api.github.com/users/lithomas1/receive...,User,False
11,xiki-tempula,6242032,MDQ6VXNlcjYyNDIwMzI=,https://avatars.githubusercontent.com/u/624203...,,https://api.github.com/users/xiki-tempula,https://github.com/xiki-tempula,https://api.github.com/users/xiki-tempula/foll...,https://api.github.com/users/xiki-tempula/foll...,https://api.github.com/users/xiki-tempula/gist...,https://api.github.com/users/xiki-tempula/star...,https://api.github.com/users/xiki-tempula/subs...,https://api.github.com/users/xiki-tempula/orgs,https://api.github.com/users/xiki-tempula/repos,https://api.github.com/users/xiki-tempula/even...,https://api.github.com/users/xiki-tempula/rece...,User,False
12,SamuelTrew,31927714,MDQ6VXNlcjMxOTI3NzE0,https://avatars.githubusercontent.com/u/319277...,,https://api.github.com/users/SamuelTrew,https://github.com/SamuelTrew,https://api.github.com/users/SamuelTrew/followers,https://api.github.com/users/SamuelTrew/follow...,https://api.github.com/users/SamuelTrew/gists{...,https://api.github.com/users/SamuelTrew/starre...,https://api.github.com/users/SamuelTrew/subscr...,https://api.github.com/users/SamuelTrew/orgs,https://api.github.com/users/SamuelTrew/repos,https://api.github.com/users/SamuelTrew/events...,https://api.github.com/users/SamuelTrew/receiv...,User,False
13,WardBrian,31640292,MDQ6VXNlcjMxNjQwMjky,https://avatars.githubusercontent.com/u/316402...,,https://api.github.com/users/WardBrian,https://github.com/WardBrian,https://api.github.com/users/WardBrian/followers,https://api.github.com/users/WardBrian/followi...,https://api.github.com/users/WardBrian/gists{/...,https://api.github.com/users/WardBrian/starred...,https://api.github.com/users/WardBrian/subscri...,https://api.github.com/users/WardBrian/orgs,https://api.github.com/users/WardBrian/repos,https://api.github.com/users/WardBrian/events{...,https://api.github.com/users/WardBrian/receive...,User,False
14,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
15,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
16,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
17,rhshadrach,45562402,MDQ6VXNlcjQ1NTYyNDAy,https://avatars.githubusercontent.com/u/455624...,,https://api.github.com/users/rhshadrach,https://github.com/rhshadrach,https://api.github.com/users/rhshadrach/followers,https://api.github.com/users/rhshadrach/follow...,https://api.github.com/users/rhshadrach/gists{...,https://api.github.com/users/rhshadrach/starre...,https://api.github.com/users/rhshadrach/subscr...,https://api.github.com/users/rhshadrach/orgs,https://api.github.com/users/rhshadrach/repos,https://api.github.com/users/rhshadrach/events...,https://api.github.com/users/rhshadrach/receiv...,User,False
18,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
19,architsingh15,15556124,MDQ6VXNlcjE1NTU2MTI0,https://avatars.githubusercontent.com/u/155561...,,https://api.github.com/users/architsingh15,https://github.com/architsingh15,https://api.github.com/users/architsingh15/fol...,https://api.github.com/users/architsingh15/fol...,https://api.github.com/users/architsingh15/gis...,https://api.github.com/users/architsingh15/sta...,https://api.github.com/users/architsingh15/sub...,https://api.github.com/users/architsingh15/orgs,https://api.github.com/users/architsingh15/repos,https://api.github.com/users/architsingh15/eve...,https://api.github.com/users/architsingh15/rec...,User,False
20,fangchenli,7614606,MDQ6VXNlcjc2MTQ2MDY=,https://avatars.githubusercontent.com/u/761460...,,https://api.github.com/users/fangchenli,https://github.com/fangchenli,https://api.github.com/users/fangchenli/followers,https://api.github.com/users/fangchenli/follow...,https://api.github.com/users/fangchenli/gists{...,https://api.github.com/users/fangchenli/starre...,https://api.github.com/users/fangchenli/subscr...,https://api.github.com/users/fangchenli/orgs,https://api.github.com/users/fangchenli/repos,https://api.github.com/users/fangchenli/events...,https://api.github.com/users/fangchenli/receiv...,User,False
21,TheNeuralBit,675055,MDQ6VXNlcjY3NTA1NQ==,https://avatars.githubusercontent.com/u/675055...,,https://api.github.com/users/TheNeuralBit,https://github.com/TheNeuralBit,https://api.github.com/users/TheNeuralBit/foll...,https://api.github.com/users/TheNeuralBit/foll...,https://api.github.com/users/TheNeuralBit/gist...,https://api.github.com/users/TheNeuralBit/star...,https://api.github.com/users/TheNeuralBit/subs...,https://api.github.com/users/TheNeuralBit/orgs,https://api.github.com/users/TheNeuralBit/repos,https://api.github.com/users/TheNeuralBit/even...,https://api.github.com/users/TheNeuralBit/rece...,User,False
22,fangchenli,7614606,MDQ6VXNlcjc2MTQ2MDY=,https://avatars.githubusercontent.com/u/761460...,,https://api.github.com/users/fangchenli,https://github.com/fangchenli,https://api.github.com/users/fangchenli/followers,https://api.github.com/users/fangchenli/follow...,https://api.github.com/users/fangchenli/gists{...,https://api.github.com/users/fangchenli/starre...,https://api.github.com/users/fangchenli/subscr...,https://api.github.com/users/fangchenli/orgs,https://api.github.com/users/fangchenli/repos,https://api.github.com/users/fangchenli/events...,https://api.github.com/users/fangchenli/receiv...,User,False
23,mwaddoups,11441393,MDQ6VXNlcjExNDQxMzkz,https://avatars.githubusercontent.com/u/114413...,,https://api.github.com/users/mwaddoups,https://github.com/mwaddoups,https://api.github.com/users/mwaddoups/followers,https://api.github.com/users/mwaddoups/followi...,https://api.github.com/users/mwaddoups/gists{/...,https://api.github.com/users/mwaddoups/starred...,https://api.github.com/users/mwaddoups/subscri...,https://api.github.com/users/mwaddoups/orgs,https://api.github.com/users/mwaddoups/repos,https://api.github.com/users/mwaddoups/events{...,https://api.github.com/users/mwaddoups/receive...,User,False
24,Dr-Irv,15113894,MDQ6VXNlcjE1MTEzODk0,https://avatars.githubusercontent.com/u/151138...,,https://api.github.com/users/Dr-Irv,https://github.com/Dr-Irv,https://api.github.com/users/Dr-Irv/followers,https://api.github.com/users/Dr-Irv/following{...,https://api.github.com/users/Dr-Irv/gists{/gis...,https://api.github.com/users/Dr-Irv/starred{/o...,https://api.github.com/users/Dr-Irv/subscriptions,https://api.github.com/users/Dr-Irv/orgs,https://api.github.com/users/Dr-Irv/repos,https://api.github.com/users/Dr-Irv/events{/pr...,https://api.github.com/users/Dr-Irv/received_e...,User,False
25,tlaytongoogle,11558041,MDQ6VXNlcjExNTU4MDQx,https://avatars.githubusercontent.com/u/115580...,,https://api.github.com/users/tlaytongoogle,https://github.com/tlaytongoogle,https://api.github.com/users/tlaytongoogle/fol...,https://api.github.com/users/tlaytongoogle/fol...,https://api.github.com/users/tlaytongoogle/gis...,https://api.github.com/users/tlaytongoogle/sta...,https://api.github.com/users/tlaytongoogle/sub...,https://api.github.com/users/tlaytongoogle/orgs,https://api.github.com/users/tlaytongoogle/repos,https://api.github.com/users/tlaytongoogle/eve...,https://api.github.com/users/tlaytongoogle/rec...,User,False
26,johnands,5294322,MDQ6VXNlcjUyOTQzMjI=,https://avatars.githubusercontent.com/u/529432...,,https://api.github.com/users/johnands,https://github.com/johnands,https://api.github.com/users/johnands/followers,https://api.github.com/users/johnands/followin...,https://api.github.com/users/johnands/gists{/g...,https://api.github.com/users/johnands/starred{...,https://api.github.com/users/johnands/subscrip...,https://api.github.com/users/johnands/orgs,https://api.github.com/users/johnands/repos,https://api.github.com/users/johnands/events{/...,https://api.github.com/users/johnands/received...,User,False
27,timlod,7346303,MDQ6VXNlcjczNDYzMDM=,https://avatars.githubusercontent.com/u/734630...,,https://api.github.com/users/timlod,https://github.com/timlod,https://api.github.com/users/timlod/followers,https://api.github.com/users/timlod/following{...,https://api.github.com/users/timlod/gists{/gis...,https://api.github.com/users/timlod/starred{/o...,https://api.github.com/users/timlod/subscriptions,https://api.github.com/users/timlod/orgs,https://api.github.com/users/timlod/repos,https://api.github.com/users/timlod/events{/pr...,https://api.github.com/users/timlod/received_e...,User,False
28,zxdawn,30388627,MDQ6VXNlcjMwMzg4NjI3,https://avatars.githubusercontent.com/u/303886...,,https://api.github.com/users/zxdawn,https://github.com/zxdawn,https://api.github.com/users/zxdawn/followers,https://api.github.com/users/zxdawn/following{...,https://api.github.com/users/zxdawn/gists{/gis...,https://api.github.com/users/zxdawn/starred{/o...,https://api.github.com/users/zxdawn/subscriptions,https://api.github.com/users/zxdawn/orgs,https://api.github.com/users/zxdawn/repos,https://api.github.com/users/zxdawn/events{/pr...,https://api.github.com/users/zxdawn/received_e...,User,False
29,HyukjinKwon,6477701,MDQ6VXNlcjY0Nzc3MDE=,https://avatars.githubusercontent.com/u/647770...,,https://api.github.com/users/HyukjinKwon,https://github.com/HyukjinKwon,https://api.github.com/users/HyukjinKwon/follo...,https://api.github.com/users/HyukjinKwon/follo...,https://api.github.com/users/HyukjinKwon/gists...,https://api.github.com/users/HyukjinKwon/starr...,https://api.github.com/users/HyukjinKwon/subsc...,https://api.github.com/users/HyukjinKwon/orgs,https://api.github.com/users/HyukjinKwon/repos,https://api.github.com/users/HyukjinKwon/event...,https://api.github.com/users/HyukjinKwon/recei...,User,False